-- CreateEnum
CREATE TYPE "Trail" AS ENUM ('FULL_STACK_JS_FRONT', 'FULL_STACK_JS_NODE', 'FULL_STACK_PY_BE', 'BE_NODEJS', 'BE_PYTHON', 'DATA_SCIENCE', 'DATA_ENGINEER', 'AI_ENGINEER');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "trail" "Trail";
