services:
  sem-patria-local-db:
    image: 'postgres:latest'
    container_name: 'sem-patria-local-db'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - my_network
    command: ['postgres', '-c', 'listen_addresses=0.0.0.0']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: node:18-alpine
    container_name: 'sem-patria-app'
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      sem-patria-local-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@sem-patria-local-db:5432/${POSTGRES_DB}
    networks:
      - my_network
    ports:
      - '3000:3000'
    command: ['sh', '-c', 'pnpm install && pnpm build && pnpm start']

networks:
  my_network:
    driver: bridge
