version: '3.8'

services:
  sem-patria-local-db:
    image: 'postgres:latest'
    container_name: 'sem-patria-local-db'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - my_network

  app:
    image: node:18-alpine
    container_name: 'sem-patria-app'
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - sem-patria-local-db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - my_network
    ports:
      - '3000:3000'
    command: ['sh', '-c', 'pnpm install && pnpm build && pnpm start']

networks:
  my_network:
    driver: bridge
