import { CaretSortIcon } from '@radix-ui/react-icons'
import {
  AlignVerticalSpaceAround,
  ArrowUpDown,
  ArrowUpRightFromCircle,
  BadgeCheck,
  Bell,
  BellDot,
  Bold,
  Bot,
  Braces,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Code,
  Codesandbox,
  Copy,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  Globe,
  GraduationCap,
  Heading1,
  Heading2,
  Heading3,
  HelpCircle,
  Home,
  Image,
  Italic,
  Layers,
  LayoutDashboard,
  List,
  ListOrdered,
  Loader2,
  Lock,
  LogOut,
  Menu,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Play,
  Plus,
  PlusCircle,
  Quote,
  Rocket,
  Send,
  Shapes,
  SlidersHorizontal,
  Sparkles,
  Strikethrough,
  Sun,
  ThumbsUp,
  Trash,
  Type,
  Underline,
  UploadCloud,
  User,
  Users,
  Video,
  X,
  type LucideIcon
} from 'lucide-react'

export type IconType = LucideIcon

export const Icons = {
  asset: FileArchive,
  lightMode: Sun,
  darkMode: Moon,
  close: X,
  check: BadgeCheck,
  arrowRight: ChevronRight,
  arrowUp: ChevronUp,
  arrowBack: ChevronLeft,
  arrowDown: ChevronDown,
  arrowUpDown: ArrowUpDown,
  arrowUpRighCircle: ArrowUpRightFromCircle,
  home: Home,
  dashboard: LayoutDashboard,
  file: File,
  user: User,
  users: Users,
  menu: Menu,
  settings: SlidersHorizontal,
  bot: Bot,
  loader: Loader2,
  code: Code,
  signOut: LogOut,
  globe: Globe,
  alignVertSA: AlignVerticalSpaceAround,
  plus: Plus,
  plusCircle: PlusCircle,
  copy: Copy,
  spread: MoreHorizontal,
  spreadVertical: MoreVertical,
  edit: Edit,
  trash: Trash,
  layers: Layers,
  calendar: CalendarCheck2,
  mentorship: GraduationCap,
  bell: Bell,
  bellDot: BellDot,
  rocket: Rocket,
  calendarDays: CalendarDays,
  calendarClock: CalendarClock,
  sparkles: Sparkles,
  play: Play,
  video: Video,
  upVote: ThumbsUp,
  moreMenu: MoreVertical,
  send: Send,
  h1: Heading1,
  h2: Heading2,
  h3: Heading3,
  bold: Bold,
  italic: Italic,
  strike: Strikethrough,
  underline: Underline,
  listBullet: List,
  listOrdered: ListOrdered,
  redirect: ExternalLink,
  classroom: Shapes,
  lock: Lock,
  codeSandbox: Codesandbox,
  checkSimple: Check,
  checkSquare: CheckSquare,
  braces: Braces,
  text: Type,
  quote: Quote,
  caretSort: CaretSortIcon,
  cloudUpload: UploadCloud,
  help: HelpCircle,
  eyeOff: EyeOff,
  eye: Eye,
  image: Image
}
