import {
  AlignVerticalSpaceAround,
  ArrowUpDown,
  ArrowUpRightFromCircle,
  BadgeCheck,
  Bell,
  BellDot,
  Bot,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Code,
  Copy,
  Edit,
  File,
  Globe,
  GraduationCap,
  Home,
  Layers,
  LayoutDashboard,
  Loader2,
  LogOut,
  Menu,
  MessageCircle,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Play,
  Plus,
  PlusCircle,
  Rocket,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Trash,
  User,
  X,
  type LucideIcon,
  ThumbsUp,
  Send,
  Heading1,
  Bold,
  Strikethrough,
  Italic,
  List,
  ListOrdered
} from 'lucide-react'

export type IconType = LucideIcon

export const Icons = {
  lightMode: Sun,
  darkMode: Moon,
  close: X,
  check: BadgeCheck,
  arrowRight: ChevronRight,
  arrowUp: ChevronUp,
  arrowBack: ChevronLeft,
  arrowDown: ChevronDown,
  arrowUpDown: ArrowUpDown,
  arrowUpRighCircle: ArrowUpRightFromCircle,
  home: Home,
  dashboard: LayoutDashboard,
  file: File,
  user: User,
  menu: Menu,
  settings: SlidersHorizontal,
  bot: Bot,
  loader: Loader2,
  code: Code,
  signOut: LogOut,
  globe: Globe,
  alignVertSA: AlignVerticalSpaceAround,
  plus: Plus,
  plusCircle: PlusCircle,
  copy: Copy,
  spread: MoreHorizontal,
  spreadVertical: MoreVertical,
  edit: Edit,
  trash: Trash,
  layers: Layers,
  calendar: CalendarCheck2,
  mentorship: GraduationCap,
  bell: Bell,
  bellDot: BellDot,
  rocket: Rocket,
  calendarDays: CalendarDays,
  calendarClock: CalendarClock,
  sparkles: Sparkles,
  videos: Play,
  upVote: ThumbsUp,
  moreMenu: MoreVertical,
  send: Send,
  h1: Heading1,
  bold: Bold,
  italic: Italic,
  strike: Strikethrough,
  listBullet: List,
  listOrdered: ListOrdered,
}
