#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Disable concurent to run `check-types` after ESLint in lint-staged
cd "$(dirname "$0")/.."
# && npx lint-staged --concurrent false

# Run Cypress tests
# pnpx cypress run --headless

# Check if Cypress tests passed
# if [ $? -ne 0 ]; then
#   echo "Cypress tests failed, aborting commit."
#   exit 1
# fi